import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ThemeProvider from "@/components/providers/ThemeProvider";
import { Toaster } from "react-hot-toast";

const geist = Geist({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geist.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <ThemeProvider>
          <header className="sticky top-0 z-50 bg-base-100">
            <Navbar />
          </header>

          <main className="py-2 md: w-11/12 mx-auto flex-1">
          {children}
          <Toaster position="top-right" />
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}